# Emit plate_water.rs v2: pixel-space rings + the typed Chart; the
# sphere is DERIVED from the map through the chart, composably.
import io
import numpy as np

TMP = r'C:/Users/donov/.claude/jobs/c6946bce/tmp'
OUT = r'C:\Users\donov\Documents\the-best-maps-ever\crates\map-adapters\src\plate_water.rs'
z = np.load(f'{TMP}/plate_water2.npz')
coef = np.load(f'{TMP}/affine.npy')  # (3,2): [x y 1] -> (lon, lat)

areas = sorted(k for k in z.files if k.startswith('area'))
jordans = sorted(k for k in z.files if k.startswith('jordan'))
rivers = sorted(k for k in z.files if k.startswith('river'))

def ring_const(name, xy):
    lines = [f"const {name}: &[(f64, f64)] = &["]
    row = []
    for x, y in xy:
        row.append(f"({x:.2f}, {y:.2f})")
        if len(row) == 5:
            lines.append("    " + ", ".join(row) + ",")
            row = []
    if row:
        lines.append("    " + ", ".join(row) + ",")
    lines.append("];")
    return "\n".join(lines)

consts, names = [], {"sea": [], "jordan": [], "river": []}
for k in areas:
    nm = "PLATE_" + k.upper().replace('-', '_')
    consts.append(ring_const(nm, z[k]))
    (names["sea"] if "great_sea" in nm.lower() else names["jordan"]).append(nm)
for i, k in enumerate(jordans):
    nm = f"PLATE_JORDAN_{i}"
    consts.append(ring_const(nm, z[k]))
    names["jordan"].append(nm)
for i, k in enumerate(rivers):
    nm = f"PLATE_RIVER_{i}"
    consts.append(ring_const(nm, z[k]))
    names["river"].append(nm)

a00, a10, b0 = coef[0][0], coef[1][0], coef[2][0]
a01, a11, b1 = coef[0][1], coef[1][1], coef[2][1]

head = '''//! The plate's water, traced in the plate's OWN pixel space
//! (generated by tools/plate_trace). The sphere is DERIVED, not
//! baked: every ring maps through `plate_chart()` — the bijective
//! pixel<->sphere chart fit over 12 detected city dots (mean residual
//! 1.6 km at ~75 m/px) — so map-space data and 3d stay one fact.
//! Lakes and the sea are traced areas; rivers are skeleton
//! centerlines rebuilt at the plate's true stroke width; the Jordan
//! is the corridor between the plate's two region fills, continuous
//! by construction. Every coordinate is a tracing marker, not a
//! place claim.

use std::collections::hash_map::DefaultHasher;
use std::hash::{Hash, Hasher};

use atlas_graph_types::covenant::{ContentHash, SourceId};
use atlas_graph_types::covenant::{Ground, Justification};
use atlas_graph_types::covenant::{BibleLocus, LocusRange, VerseRef};
use atlas_graph_types::covenant::TimePoint;

use map_types::chart::Chart;
use map_types::{
    Boundary, BoundaryHistory, BoundaryId, BoundarySource, EdgeCharacter, Interval, Orientation,
    RegionClass, RegionGeom, RegionHistory, RegionId, RegionPart, UnitVec, WorldTimeline,
};

pub const PLATE_PROVENANCE: &str =
    "authored:plate-trace (georeferenced reference plate; affine over 12 city dots, mean 1.6 km)";

/// The plate's chart: pixel -> sphere, bijective on the plate frame.
pub fn plate_chart() -> Chart {
    Chart::new(
        [[%(a00).12e, %(a01).12e], [%(a10).12e, %(a11).12e]],
        [%(b0).12e, %(b1).12e],
        (0.0, 0.0, 4500.0, 6000.0),
    )
    .expect("the plate chart is non-degenerate")
}

''' % {"a00": a00, "a01": a01, "a10": a10, "a11": a11, "b0": b0, "b1": b1}

mid = "\n\n".join(consts)

def parts_list(ns):
    return ", ".join(ns)

tail = '''

fn hash_id(tag: &str) -> ContentHash {
    let mut h = DefaultHasher::new();
    tag.hash(&mut h);
    ContentHash(h.finish())
}

/// The plate's water as a timeline of RegionClass::Water regions,
/// every point derived from plate pixels through `plate_chart()`.
pub fn plate_water_timeline(from: TimePoint) -> WorldTimeline {
    let gen_1_9_10 = || {
        let v = |verse| BibleLocus::whole(VerseRef { book: 1, chapter: 1, verse });
        LocusRange::new(v(9), v(10)).expect("GEN 1:9-10 is ordered")
    };
    let source = SourceId::new("authored:plate-trace");
    let justification = Justification {
        text: Some(
            "\\"the gathering together of the waters called he Seas\\" — shapes derived \\
             from the reference plate through its chart (see provenance)."
                .to_string(),
        ),
        grounds: [Ground::Scripture(gen_1_9_10()), Ground::Source(source.clone())].into(),
    };
    let valid = Interval { from, to: None };
    let chart = plate_chart();
    let mut tl = WorldTimeline::default();

    let mut part = |tl: &mut WorldTimeline, tag: &str, ring: &[(f64, f64)]| -> RegionPart {
        let mut pts: Vec<UnitVec> = ring
            .iter()
            .map(|(x, y)| chart.to_sphere(*x, *y).expect("plate rings live on the plate"))
            .collect();
        pts.push(pts[0]);
        let bid = BoundaryId(hash_id(&format!("plate-water/{tag}")));
        tl.boundaries.insert(
            bid,
            BoundaryHistory {
                versions: vec![(
                    valid,
                    Boundary {
                        pts,
                        character: EdgeCharacter::Line,
                        source: BoundarySource::Imported { source: source.clone() },
                        justification: justification.clone(),
                        provenance: PLATE_PROVENANCE.to_string(),
                    },
                )],
            },
        );
        RegionPart { cycle: vec![(bid, Orientation::Forward)], holes: Vec::new() }
    };

    let mut region = |tl: &mut WorldTimeline, key: &str, label: &str, rings: &[&[(f64, f64)]]| {
        let parts: Vec<RegionPart> = rings
            .iter()
            .enumerate()
            .map(|(i, ring)| part(tl, &format!("{key}-{i}"), ring))
            .collect();
        tl.regions.insert(
            RegionId(hash_id(&format!("plate-water/{key}"))),
            RegionHistory {
                class: RegionClass::Water,
                label_history: vec![(valid, label.to_string())],
                geom_history: vec![(valid, RegionGeom { parts })],
            },
        );
    };

    region(&mut tl, "great-sea", "the Great Sea (plate)", &[SEA_PARTS]);
    region(&mut tl, "jordan-waters", "the waters of the Jordan (plate)", &[JORDAN_PARTS]);
    region(&mut tl, "rivers", "the rivers of the land (plate)", &[RIVER_PARTS]);
    tl
}
'''
tail = tail.replace("[SEA_PARTS]", "[" + parts_list(names["sea"]) + "]")
tail = tail.replace("[JORDAN_PARTS]", "[" + parts_list(names["jordan"]) + "]")
tail = tail.replace("[RIVER_PARTS]", "[" + parts_list(names["river"]) + "]")

io.open(OUT, 'w', encoding='utf8', newline='').write(head + mid + tail)
n = sum(len(z[k]) for k in z.files)
print(f"wrote plate_water.rs v2: {len(areas)} areas, {len(jordans)} jordan parts, {len(rivers)} rivers, {n} ring points")
