# Emit crates/map-adapters/src/plate_water.rs from the traced rings.
import io
import numpy as np

TMP = r'C:/Users/donov/.claude/jobs/c6946bce/tmp'
OUT = r'C:\Users\donov\Documents\the-best-maps-ever\crates\map-adapters\src\plate_water.rs'
z = np.load(f'{TMP}/plate_water.npz')
rings = [z['part0'], z['part1'], z['part2']]  # (lon, lat) each

def ring_const(name, ll):
    lines = [f"const {name}: &[(f64, f64)] = &["]
    row = []
    for lon, lat in ll:
        row.append(f"({lat:.5f}, {lon:.5f})")
        if len(row) == 4:
            lines.append("    " + ", ".join(row) + ",")
            row = []
    if row:
        lines.append("    " + ", ".join(row) + ",")
    lines.append("];")
    return "\n".join(lines)

head = '''//! The plate's water, traced (generated by tools/plate_trace).
//!
//! The owner's reference plate is a WITNESS: its seas and rivers were
//! georeferenced (affine over 12 detected city dots, mean residual
//! 1.6 km at ~75 m/px) and their color-mask contours traced, so the
//! water sits flush against the plate-traced region borders — the
//! same hand drew both. Rings ride here as (lat, lon) pairs; every
//! coordinate is a tracing marker, not a place claim.

use std::collections::hash_map::DefaultHasher;
use std::hash::{Hash, Hasher};

use atlas_graph_types::covenant::{ContentHash, SourceId};
use atlas_graph_types::covenant::{Ground, Justification};
use atlas_graph_types::covenant::{BibleLocus, LocusRange, VerseRef};
use atlas_graph_types::covenant::TimePoint;

use map_types::{
    Boundary, BoundaryHistory, BoundaryId, BoundarySource, EdgeCharacter, Interval, Orientation,
    RegionClass, RegionGeom, RegionHistory, RegionId, RegionPart, UnitVec, WorldTimeline,
};

pub const PLATE_PROVENANCE: &str =
    "authored:plate-trace (georeferenced reference plate; affine over 12 city dots, mean 1.6 km)";

'''

body = []
body.append(ring_const("PLATE_GREAT_SEA", rings[0]))
body.append(ring_const("PLATE_JORDAN_WATERS", rings[1]))
body.append(ring_const("PLATE_HERMON_STREAMS", rings[2]))

tail = '''

fn hash_id(tag: &str) -> ContentHash {
    let mut h = DefaultHasher::new();
    tag.hash(&mut h);
    ContentHash(h.finish())
}

/// The plate's water as a timeline: RegionClass::Water regions from
/// the creation anchor onward, one region for the Great Sea and one
/// for the Jordan and its seas (the Hermon headwaters ride as a
/// second part). Bridged into the canon Water layer as the Authored
/// witness beside natural-earth.
pub fn plate_water_timeline(from: TimePoint) -> WorldTimeline {
    let gen_1_9_10 = || {
        let v = |verse| BibleLocus::whole(VerseRef { book: 1, chapter: 1, verse });
        LocusRange::new(v(9), v(10)).expect("GEN 1:9-10 is ordered")
    };
    let source = SourceId::new("authored:plate-trace");
    let justification = Justification {
        text: Some(
            "\\"the gathering together of the waters called he Seas\\" — shapes traced \\
             from the owner's reference plate (see provenance)."
                .to_string(),
        ),
        grounds: [Ground::Scripture(gen_1_9_10()), Ground::Source(source.clone())].into(),
    };
    let valid = Interval { from, to: None };
    let mut tl = WorldTimeline::default();

    let mut part = |tl: &mut WorldTimeline, tag: &str, ring: &[(f64, f64)]| -> RegionPart {
        let mut pts: Vec<UnitVec> =
            ring.iter().map(|(la, lo)| UnitVec::from_lat_lon_deg(*la, *lo)).collect();
        pts.push(pts[0]);
        let bid = BoundaryId(hash_id(&format!("plate-water/{tag}")));
        tl.boundaries.insert(
            bid,
            BoundaryHistory {
                versions: vec![(
                    valid,
                    Boundary {
                        pts,
                        character: EdgeCharacter::Line,
                        source: BoundarySource::Imported { source: source.clone() },
                        justification: justification.clone(),
                        provenance: PLATE_PROVENANCE.to_string(),
                    },
                )],
            },
        );
        RegionPart { cycle: vec![(bid, Orientation::Forward)], holes: Vec::new() }
    };

    let sea = part(&mut tl, "great-sea", PLATE_GREAT_SEA);
    tl.regions.insert(
        RegionId(hash_id("plate-water/the Great Sea")),
        RegionHistory {
            class: RegionClass::Water,
            label_history: vec![(valid, "the Great Sea (plate)".to_string())],
            geom_history: vec![(valid, RegionGeom { parts: vec![sea] })],
        },
    );
    let jordan = part(&mut tl, "jordan-waters", PLATE_JORDAN_WATERS);
    let hermon = part(&mut tl, "hermon-streams", PLATE_HERMON_STREAMS);
    tl.regions.insert(
        RegionId(hash_id("plate-water/the waters of the Jordan")),
        RegionHistory {
            class: RegionClass::Water,
            label_history: vec![(valid, "the waters of the Jordan (plate)".to_string())],
            geom_history: vec![(valid, RegionGeom { parts: vec![jordan, hermon] })],
        },
    );
    tl
}
'''

io.open(OUT, 'w', encoding='utf8', newline='').write(head + "\n\n".join(body) + tail)
print("wrote plate_water.rs:", sum(len(r) for r in rings), "ring points")
