module Prop where

import Data.Bits (xor)
import qualified Data.ByteString as BS
import Data.Map.Strict (Map)
import qualified Data.Map.Strict as Map
import qualified Data.Set as Set
import Data.Text (Text)
import qualified Data.Text as T
import qualified Data.Text.Encoding as TE
import Data.Word (Word64)
import Test.QuickCheck
import Test.QuickCheck.Gen (Gen (..), unGen)
import Test.QuickCheck.Random (mkQCGen)
import Capture
import Gherkin.Ast
import Gherkin.Parse (parseFeature)
import Run
import World (StepDef, World, readFeatureFile)

-- ---------- holes, drawn in CORRELATED GROUPS ----------
--
-- A hole is not always independent of its neighbours. Three of this
-- corpus's laws are about a RELATIONSHIP between two drawn values, and
-- they are vacuous unless the draw establishes it:
--
--   * dress-locality quantifies over <someStyle> and <someOtherStyle>.
--     Two independent draws from the three styles collide one time in
--     three, and a "restyle" to the SAME style leaves the two bodies
--     identical, which the step then reports as "dress did not actually
--     change" -- a red that says nothing about the server.
--   * the subtractive law quantifies over <someSubset> and
--     <someSuperset>. Two independent piece sets are nested only by
--     luck; the law would spend most of its iterations red for a reason
--     that is not a fact about the server either.
--
-- The trap this project has already fallen into once (fix 7cd31bd:
-- someA/someB drew the IDENTICAL value from one iteration-only seed, so
-- the composition law degenerated to `x == x ∪ x` and could not fail) is
-- the same trap seen from the other side. Correlation by ACCIDENT made a
-- law unfalsifiable; correlation on PURPOSE makes these laws checkable —
-- and the difference between the two is entirely whether the
-- relationship is declared, generated by construction, and pinned by a
-- test that would fail if it broke. So correlation is a first-class
-- thing here, not a special case in the substitution code:
--
-- A GROUP is the unit of drawing. Its members are drawn TOGETHER, from
-- ONE seed, by ONE generator that establishes whatever relationship
-- holds between them. An ordinary independent hole is the degenerate
-- group of one (`solo`), so there is a single drawing rule, not two.
data HoleGroup = HoleGroup
  { groupName    :: Text
    -- ^ the group's own identity — what its seed is keyed on. For a solo
    -- group this IS the hole's name, so solo holes keep the exact seeds
    -- (and therefore the exact draws) they had before groups existed.
  , groupMembers :: [Text]
    -- ^ every hole name this group binds. Must be disjoint from every
    -- other group's (pinned as a law: `holeRegistry` is a partition).
  , groupDraw    :: Gen (Map Text Text)
    -- ^ ONE draw, producing the rendered binding for every member at
    -- once. Rendering (rather than a typed existential) happens inside
    -- the generator because that is where the members' types are still
    -- known; a group can mix types freely without the registry needing
    -- to know about it.
  }

-- The degenerate group: one hole, drawn on its own, exactly as before.
solo :: FromCapture a => Text -> Gen a -> HoleGroup
solo n g = HoleGroup n [n] (Map.singleton n . renderCap <$> g)

-- A two-member correlated group: ONE generator produces both values, so
-- whatever relation it establishes between them is true BY CONSTRUCTION
-- of every draw, not true on average or true after a retry.
pair :: (FromCapture a, FromCapture b) => Text -> Text -> Text -> Gen (a, b) -> HoleGroup
pair gname n1 n2 g = HoleGroup gname [n1, n2] $ do
  (a, b) <- g
  pure (Map.fromList [(n1, renderCap a), (n2, renderCap b)])

-- A possibly-empty subset of every piece. R6/the scene's own algebra:
-- the empty scene is the monoid identity, and `sublistOf` genuinely
-- includes `[]` in its codomain, so the identity IS reachable here —
-- see the "genPieces can generate the empty piece set" test, which
-- samples this generator directly to prove it, not just trust the docs.
genPieces :: Gen PieceSet
genPieces = PieceSet . Set.fromList <$> sublistOf [minBound .. maxBound]

-- Final-review Fix 3: year 0 does not exist in this calendar (see
-- Capture.hs's Year instance) -- excluded from the generator's codomain
-- by the same law, not merely by the server happening to reject it after
-- the fact. `suchThat` retries on the one excluded value out of 4105;
-- negligible cost, no risk of divergence.
genYear :: Gen Year
genYear = Year <$> chooseInt (-4004, 100) `suchThat` (/= 0)

-- <someStyle> / <someOtherStyle>: two styles that are DISTINCT BY
-- CONSTRUCTION.
--
-- Not `suchThat (/=)` (rejection sampling, which is distinctness by
-- retry — correct, but it makes "can these ever collide?" a question
-- about the sampler's luck rather than about the generator's codomain),
-- and emphatically not "draw twice and hope". Draw one style, then
-- rotate by a NON-ZERO offset in Z_n: `i` and `i + d` are different
-- residues for every `d` in 1..n-1, so no draw this generator can
-- produce has the two equal. The distinctness test over a run of
-- iterations is then pinning a property the construction already
-- guarantees, which is exactly the right relationship between a law and
-- its test.
--
-- Requires at least two dresses to exist at all (a "different style"
-- is not a thing you can ask for in a one-style world) — pinned as its
-- own test rather than left as an implicit assumption of the modulus.
genStylePair :: Gen (StyleName, StyleName)
genStylePair = do
  i <- chooseInt (0, n - 1)
  d <- chooseInt (1, n - 1)
  pure (styleAt i, styleAt (i + d))
  where
    n = length styleNames
    styleAt k = StyleName (styleNames !! (k `mod` n))

-- <someSubset> / <someSuperset>: a NESTED pair, by construction.
--
-- Draw the superset first, then draw the subset from INSIDE it, so
-- `subset ⊆ superset` holds for every draw this generator can produce —
-- there is no draw in its codomain that violates the nesting, so the
-- subtractive law never spends an iteration red for a reason that has
-- nothing to do with the server.
--
-- Equality (subset == superset) is a LEGAL draw and is deliberately not
-- excluded: `fewer ⊆ more` is a claim about ⊆, and the reflexive case is
-- part of what it claims. But a law tested only on equal sets tests
-- nothing about subtraction, so the DISTRIBUTION matters as much as the
-- codomain: `sublistOf` keeps each of the superset's k pieces
-- independently, so the two coincide with probability 2^-k, and
-- averaging over the superset's own sublistOf draw gives
-- (3/2)^10 / 2^10 ≈ 5.6% — i.e. roughly 94% of draws are PROPER
-- subsets. The distribution test pins a floor of a quarter: far below
-- what the construction actually delivers (so it is not a threshold
-- tuned to today's numbers), far above zero (so a future change that
-- collapsed the pair into equality would fail it loudly).
genNestedPieces :: Gen (PieceSet, PieceSet)
genNestedPieces = do
  PieceSet super <- genPieces
  sub <- sublistOf (Set.toList super)
  pure (PieceSet (Set.fromList sub), PieceSet super)

-- The one and only place a hole name is given meaning. EXPLICIT and
-- TYPED, no name-sniffing/inference: a hole not listed here has no
-- generator, and `runScenarioProperty`/`substituteExamples` must treat
-- that as a loud failure, never a silent pass (requirement 1).
--
-- someA and someB stay SEPARATE solo groups: the composition law needs
-- them independent (that is what fix 7cd31bd restored), and independence
-- is now the structural consequence of being in different groups rather
-- than a property of the seeding formula alone.
holeGroups :: [HoleGroup]
holeGroups =
  [ solo "someYear"   genYear
  , solo "somePieces" genPieces
  , solo "someA"      genPieces
  , solo "someB"      genPieces
  , pair "stylePair"     "someStyle"  "someOtherStyle" genStylePair
  , pair "nestedPieces"  "someSubset" "someSuperset"   genNestedPieces
  ]

-- Every hole name, mapped to the group that draws it. A partition of the
-- hole names, not merely a map into groups: `check` asks this for
-- membership (an unregistered hole is an orphan), and the runner asks it
-- which groups a scenario's holes belong to.
holeRegistry :: Map Text HoleGroup
holeRegistry = Map.fromList [ (h, g) | g <- holeGroups, h <- groupMembers g ]

-- Every "<hole>" token appearing in one raw step body, left to right.
-- Exported (not just used internally by `holesOf`) so `Check.classify`
-- can scan a bare `Step`'s body for holes too, without going through a
-- whole `Scenario` -- that's what lets an UNREGISTERED hole be caught at
-- `check` time regardless of which capture it happens to land in.
holesIn :: Text -> [Text]
holesIn b = case T.breakOn "<" b of
  (_, rest) | T.null rest -> []
  (_, rest) ->
    let (h, rest') = T.breakOn ">" (T.drop 1 rest)
    in h : if T.null rest' then [] else holesIn (T.drop 1 rest')

-- Every "<hole>" token appearing in any step body of a scenario, in
-- first-seen order (duplicates removed by `dedupe` at the call site).
holesOf :: Scenario -> [Text]
holesOf sc = concatMap (holesIn . stepBody) (scSteps sc)

-- First-seen order, genuinely -- a naive `foldr (\x acc -> if x \`elem\`
-- acc then acc else x : acc) []` looks right but actually REVERSES
-- relative order among the first occurrences (try it on [a,b,a,c]: it
-- yields [b,a,c], not [a,b,c]), because foldr conses the LATEST
-- not-yet-seen element it encounters (scanning right-to-left) onto the
-- front. Harmless everywhere this is currently used -- binding lookup is
-- by Map key, and the failing-binding report sorts by key too -- but the
-- name promises an order this shape doesn't deliver, so it earns an
-- explicit accumulator instead.
dedupe :: [Text] -> [Text]
dedupe = go []
  where
    go _ [] = []
    go seen (x : xs)
      | x `elem` seen = go seen xs
      | otherwise     = x : go (x : seen) xs

-- Every "<hole>" token in every step of a scenario gets textually
-- replaced by its bound rendering. `env` need not cover every hole in
-- `sc` for this to typecheck (it's just Text -> Text substitution) --
-- callers (runScenarioProperty, below) are the ones responsible for
-- ensuring every hole actually used has a binding first.
substitute :: Map Text Text -> Scenario -> Scenario
substitute env sc = sc { scSteps = map sub (scSteps sc) }
  where
    sub st = st { stepBody = Map.foldrWithKey
                    (\h v b -> T.replace ("<" <> h <> ">") v b)
                    (stepBody st) env }

-- Final-review Fix 1 (Critical): the seed a hole draws from is a function
-- of BOTH the hole's own name and the iteration index, never the index
-- alone. The pre-fix version (`mkQCGen (fromIntegral i * 7919)`, keyed
-- ONLY on `i`) meant every hole bound at the same iteration -- regardless
-- of name -- drew from the identical point in the identical generator's
-- stream. That is invisible for two DIFFERENT generators (Year vs.
-- PieceSet can't collide), but scene.feature's composition property
-- registers `someA` and `someB` against the SAME generator (`genPieces`,
-- see holeRegistry below): `unGen` is pure, so same generator + same
-- QCGen + same size is the same value, every iteration, for the whole
-- run. someA and someB were therefore never actually independent --
-- always literally the same PieceSet -- which makes the composition
-- law's assertion (`sceneA \`union\` sceneB == union of the parts`)
-- degenerate to `x == x \`union\` x`, true for ANY server behaviour. A
-- "target already met" verdict built on that is an artifact of the
-- generator wiring, not a fact about the server (see MEMORY:
-- verify-distinct-not-nonnull -- a check satisfiable by the failure mode
-- is no check).
--
-- Still fully deterministic (requirement 2: the same scenario run twice
-- must generate the exact same bindings and verdict, including a failing
-- run's counterexample text) -- `holeSeed` is a pure function of
-- (name, i), so nothing here depends on wall-clock time or any other
-- live entropy; the "same scenario run twice" test still holds.
--
-- FNV-1a over the hole name's UTF-8 bytes, folded with the per-iteration
-- multiplier the old code already used: a real, cheap, well-distributed
-- combination of both inputs, not a tuned magic constant chosen to make
-- any particular scenario pass -- the SAME formula runs for every hole,
-- known-colliding or not.
holeSeed :: Text -> Int -> Int
holeSeed name i = fromIntegral (fnv1a (TE.encodeUtf8 name)) * 7919 + i
  where
    fnv1a :: BS.ByteString -> Word64
    fnv1a = BS.foldl' step offsetBasis
    offsetBasis = 14695981039346656037 :: Word64
    prime = 1099511628211 :: Word64
    step h b = (h `xor` fromIntegral b) * prime

-- Draw one GROUP at a given iteration index, keyed by the group's own
-- name too (see `holeSeed` above) -- so two groups sharing a generator
-- in the SAME scenario iteration (someA/someB) draw from genuinely
-- independent points in that generator's stream, instead of both landing
-- on the identical value. Members WITHIN a group share this one draw:
-- that is the whole point of a group, and the only way a relationship
-- between two holes can be established at all.
drawGroup :: HoleGroup -> Int -> Map Text Text
drawGroup g i =
  unGen (groupDraw g) (mkQCGen (holeSeed (groupName g) i)) (min 30 (i + 3))

-- The bindings a scenario mentioning exactly `hs` gets at iteration `i`.
--
-- Each group is drawn ONCE per iteration however many of its members the
-- scenario happens to mention (so a scenario using only <someStyle> gets
-- the same value it would have got alongside <someOtherStyle>), and the
-- result is restricted back to the holes actually present, so a failing
-- iteration's counterexample reports the bindings the scenario really
-- used and nothing else.
--
-- Exported because the correlation LAWS are tested against this, the
-- real thing the runner calls, rather than against a reconstruction of
-- it in the test file.
bindingsFor :: [Text] -> Int -> Map Text Text
bindingsFor hs i =
  Map.restrictKeys drawn (Set.fromList hs)
  where
    groups = Map.fromList [ (groupName g, g) | h <- hs, Just g <- [Map.lookup h holeRegistry] ]
    drawn  = Map.unions [ drawGroup g i | g <- Map.elems groups ]

-- Run one @property-tagged scenario N times over generated bindings. A
-- scenario with no holes at all is a harmless (if wasteful) degenerate
-- case: every iteration substitutes nothing and re-runs the same body.
--
-- Iterations are counted, not just consumed: a `Skipped` iteration (a
-- draw whose binding cannot exercise this law's precondition -- see
-- World.StepOutcome) is neither a pass nor a failure, and `Run.lawTally`
-- turns an all-skipped run into a Failed naming the count, because a law
-- that never ran must not report green.
runScenarioProperty :: [StepDef] -> World -> Int -> Scenario -> IO LawRun
runScenarioProperty defs w n sc =
  case unregistered of
    (h : _) -> pure $ LawRun
      (Failed ("unregistered property hole <" <> h <> "> in scenario \""
               <> scName sc <> "\" -- add it to Prop.holeRegistry")) 0
    [] -> loop 0 0 ""
  where
    hs = dedupe (holesOf sc)
    unregistered = [ h | h <- hs, h `Map.notMember` holeRegistry ]
    loop i skips lastWhy
      | i >= n = pure (lawTally n skips lastWhy Passed)
      | otherwise = do
          let env = bindingsFor hs i
          v <- runScenario defs w (substitute env sc)
          case v of
            Passed -> loop (i + 1) skips lastWhy
            -- The skipped iteration still names the binding that could
            -- not exercise the law: "12 skipped" without a single
            -- example of WHY is a number nobody can act on.
            Skipped why -> loop (i + 1) (skips + 1) (why <> withBindings env)
            Failed e -> pure (LawRun (Failed (e <> withBindings env)) skips)
    withBindings env = "\n    with " <> T.intercalate ", "
      [ h <> " = " <> val | (h, val) <- Map.toList env ]

-- For the totality check ONLY (Check.dehole, applied only when the
-- enclosing scenario is @property-tagged — see Check.hs): every
-- registered hole in a raw step body is replaced with ONE fixed,
-- deterministic example value (seed 1, size 3 — arbitrary but stable),
-- so a capture that validates its input (Piece, Year, Style) sees a real
-- value instead of literal "<hole>" text, and a capture that does NOT
-- validate (UrlPath, which only rejects whitespace) is not fooled into
-- matching on a hole that merely happens to contain no whitespace of its
-- own (ruling R33). An UNREGISTERED hole is deliberately left untouched
-- here — it is not this function's job to fail loudly (it has no
-- scenario to name in an error). `Check.classify` scans for that case
-- itself, BEFORE calling this function, using `holesIn` above; the
-- run-time equivalent (naming the scenario too) is
-- `runScenarioProperty`'s own check, just above.
-- THE gate: whether a scenario with these tags gets its holes substituted
-- before a step body is examined statically.
--
-- Review finding (round 1, Important): this rule used to exist TWICE --
-- `Check.classify` and `Vocab.expectedVocab` each re-expressed "if the
-- scenario is @property-tagged, substitute; otherwise don't" in their own
-- words, with no shared function and nothing pinning the two copies
-- together. Same predicate, same substitution, two independent
-- definitions: the layer-name-twice defect class. The moment the gate
-- becomes feature-tag-aware, or the substitution becomes scenario-aware,
-- the two copies diverge SILENTLY -- and the symptom is not a red test
-- but a deleted or wrong Vocabulary block in the owner's hand-written
-- corpus, discovered by a human reading a file.
--
-- One function, called by both. The gate's REASONING lives in Check.hs's
-- comment (which spells out the mirror-image consequences of getting it
-- wrong in either direction); this is the single place it is DECIDED.
-- The condition is exactly the one `Prop.runWithProperties`'s `run1`
-- uses to decide whether to substitute at run time, which is the fact
-- both static callers are trying to predict.
deholeFor :: [Tag] -> Text -> Text
deholeFor tags
  | Tag "property" `elem` tags = substituteExamples
  | otherwise                  = id

substituteExamples :: Text -> Text
substituteExamples b0 = foldr rep b0 (concatMap example holeGroups)
  where
    -- One draw per GROUP, so a correlated group's example values are
    -- related to each other here exactly the way they will be at run
    -- time -- `check` never sees a subset/superset pair that a real
    -- iteration could not have produced.
    example g = Map.toList (unGen (groupDraw g) (mkQCGen 1) 3)
    rep :: (Text, Text) -> Text -> Text
    rep (h, v) = T.replace ("<" <> h <> ">") v

-- How many iterations a @property law must run, or why the requested
-- count is not a count at all.
--
-- Review finding (round 1): `--property-runs 0` is not a CHEAP run, it
-- is a SILENT one. With no iterations, `runScenarioProperty`'s loop
-- terminates immediately having examined nothing; `lawTally`'s
-- `iterations > 0` guard cannot fire (0 skipped of 0 is not "all
-- skipped" by any honest reading); and every @property law in both
-- corpora reports a green tick for zero evidence. That is the precise
-- failure this whole stage exists to outlaw -- a check satisfiable by
-- its own failure mode (MEMORY: verify-distinct-not-nonnull) -- and the
-- knob that produces it is the one CI budget pressure reaches for
-- first. So it is refused at PARSE time, loudly, rather than accepted
-- into a run whose table looks like a pass.
--
-- Lives here, not in the option parser, so the law is testable: the
-- executable's reader is a two-line adapter over this function (app/
-- Main.hs), and Spec pins both directions against the function itself.
checkPropertyRuns :: Int -> Either String Int
checkPropertyRuns n
  | n >= 1 = Right n
  | otherwise = Left $
      "--property-runs must be at least 1 (got " <> show n <> "). "
        <> "A run of " <> show n <> " iterations does not check a @property law "
        <> "less thoroughly -- it does not check it at all, and every such law "
        <> "would report green having examined nothing."

-- Plain scenarios run once; @property scenarios run `n` times over
-- generated bindings (first failure's Verdict already carries its
-- binding values, from runScenarioProperty above).
runWithProperties :: [StepDef] -> World -> Int -> [FilePath] -> IO [ScenarioResult]
runWithProperties defs w n files = fmap concat . mapM one $ files
  where
    one p = do
      -- Fix 4: shared explicit-UTF-8 reader, not a plain TIO.readFile --
      -- see World.readFeatureFile's comment.
      src <- readFeatureFile p
      case parseFeature p src of
        Left e  -> pure [ScenarioResult (T.pack p) "PARSE" [] (Failed e) 0]
        Right f -> mapM (run1 (ftTitle f)) (ftScenarios f)
    run1 ft sc
      | Tag "property" `elem` scTags sc =
          mk ft sc <$> runScenarioProperty defs w n sc
      | otherwise =
          mk ft sc . lawOnce <$> runScenario defs w sc
    mk ft sc (LawRun v s) = ScenarioResult ft (scName sc) (scTags sc) v s
