module Prop where

import Data.Bits (xor)
import qualified Data.ByteString as BS
import Data.List (nub, tails)
import Data.Map.Strict (Map)
import Data.Proxy (Proxy (..))
import qualified Data.Map.Strict as Map
import qualified Data.Set as Set
import Data.Text (Text)
import qualified Data.Text as T
import qualified Data.Text.Encoding as TE
import Data.Word (Word64)
import Test.QuickCheck
import Test.QuickCheck.Gen (Gen (..), unGen)
import Test.QuickCheck.Random (mkQCGen)
import Capture
import Gherkin.Ast
import Gherkin.Parse (parseFeature)
import Run
import World (StepDef, World, readFeatureFile)

-- ---------- holes, drawn in CORRELATED GROUPS ----------
--
-- A hole is not always independent of its neighbours. Three of this
-- corpus's laws are about a RELATIONSHIP between two drawn values, and
-- they are vacuous unless the draw establishes it:
--
--   * dress-locality quantifies over <someStyle> and <someOtherStyle>.
--     Two independent draws from the three styles collide one time in
--     three, and a "restyle" to the SAME style leaves the two bodies
--     identical, which the step then reports as "dress did not actually
--     change" -- a red that says nothing about the server.
--   * the subtractive law quantifies over <someSubset> and
--     <someSuperset>. Two independent piece sets are nested only by
--     luck; the law would spend most of its iterations red for a reason
--     that is not a fact about the server either.
--
-- The trap this project has already fallen into once (fix 7cd31bd:
-- someA/someB drew the IDENTICAL value from one iteration-only seed, so
-- the composition law degenerated to `x == x ∪ x` and could not fail) is
-- the same trap seen from the other side. Correlation by ACCIDENT made a
-- law unfalsifiable; correlation on PURPOSE makes these laws checkable —
-- and the difference between the two is entirely whether the
-- relationship is declared, generated by construction, and pinned by a
-- test that would fail if it broke. So correlation is a first-class
-- thing here, not a special case in the substitution code:
--
-- A GROUP is the unit of drawing. Its members are drawn TOGETHER, from
-- ONE seed, by ONE generator that establishes whatever relationship
-- holds between them. An ordinary independent hole is the degenerate
-- group of one (`solo`), so there is a single drawing rule, not two.
data HoleGroup = HoleGroup
  { groupName    :: Text
    -- ^ the group's own identity — what its seed is keyed on. For a solo
    -- group this IS the hole's name, so solo holes keep the exact seeds
    -- (and therefore the exact draws) they had before groups existed.
  , groupMembers :: [Text]
    -- ^ every hole name this group binds. Must be disjoint from every
    -- other group's (pinned as a law: `holeRegistry` is a partition).
  , groupDraw    :: Gen (Map Text Text)
    -- ^ ONE draw, producing the rendered binding for every member at
    -- once. Rendering (rather than a typed existential) happens inside
    -- the generator because that is where the members' types are still
    -- known; a group can mix types freely without the registry needing
    -- to know about it.
  , groupShrink  :: Map Text Text -> [Map Text Text]
    -- ^ Spec §4's other half of a hole's contract: from the bindings a
    -- failing iteration actually used, the strictly smaller bindings
    -- worth trying instead. The GROUP is the unit here for the same
    -- reason it is the unit of drawing -- a candidate that re-bound only
    -- half of a correlated pair could hand the law a binding no draw
    -- could ever have produced, and a counterexample that is not an
    -- example of anything is worse than a large one. So a candidate
    -- replaces EVERY member at once and owes `groupLaw` below, exactly
    -- as `groupDraw` does.
    --
    -- Rendered in, rendered out: candidates are derived from the CURRENT
    -- values (parse -> shrink -> re-render), never from a fresh draw, so
    -- shrinking consumes no randomness and the same failing run always
    -- walks the same path to the same minimum.
  , groupRank    :: Map Text Text -> Int
    -- ^ How BIG this group's bindings are, as a natural number. Every
    -- candidate `groupShrink` offers must have a strictly smaller rank
    -- than the bindings it came from; since the rank is a bounded
    -- natural, no sequence of shrinks can go on forever, and none can
    -- return to a value it has already left. That is what makes the
    -- greedy loop terminate -- see `shrinkToMinimal`, where the fuel
    -- bound is then a backstop against a mis-written shrinker rather
    -- than the thing that ends a normal run.
  , groupLaw     :: Map Text Text -> Bool
    -- ^ The relationship this group establishes, as a predicate over
    -- rendered bindings. Declared on the group rather than restated in
    -- the test file so that a NEW correlated group cannot be added
    -- without saying what it correlates -- the relationship is then owed
    -- by the generator and the shrinker alike, and one test pins both.
    -- `const True` for a solo group, which establishes nothing.
  }

-- What it means for one of a group's drawn values to be SMALLER, as one
-- value rather than two loose functions: a shrinking ORDER is a rank
-- together with the candidates it admits, and the pairing is the whole
-- content of the contract ("every candidate ranks strictly lower"). Kept
-- together so a shrinker cannot be written, or changed, without saying
-- what it is shrinking WITH RESPECT TO -- which is exactly the step the
-- first draft of this task skipped, and it cost a real cycle: -1405 and
-- -1400 each offered the other, and only the fuel bound stopped the
-- loop (see `yearRank`).
data Order a = Order
  { rankOf     :: a -> Int
  , shrinkWith :: a -> [a]
  }

-- The degenerate group: one hole, drawn on its own, exactly as before,
-- and shrunk on its own -- a solo group correlates nothing, so its law
-- is trivially true and its candidates are just its member's.
solo :: FromCapture a => Text -> Gen a -> Order a -> HoleGroup
solo n g o = soloLawful n g o (const True)

-- A solo group WITH a law. A group of one correlates nothing with a
-- partner, but it can still owe a property of its own -- <someZoom>
-- does: the two cameras camera.feature derives from it ("doubled",
-- "halved") must be other cameras, or the laws quantified over it
-- compare a scene with itself. `solo` is this at `const True`, so
-- there is still ONE drawing rule and one shrinking rule, not two, and
-- the generic pins (every draw and every candidate satisfies its
-- group's law) reach a lawful solo group for free.
soloLawful :: FromCapture a => Text -> Gen a -> Order a -> (Map Text Text -> Bool) -> HoleGroup
soloLawful n g o lawful = HoleGroup n [n] (Map.singleton n . renderCap <$> g) sh rk lawful
  where
    sh env = [ Map.singleton n r
             | Right a <- [bound1 n env], a' <- shrinkWith o a, r <- renderLawful a' ]
    -- An unreadable binding ranks 0 and shrinks to nothing: it is the
    -- bottom of the order in both, so the two answers agree instead of
    -- one of them quietly claiming progress the other cannot make.
    rk env = either (const 0) (rankOf o) (bound1 n env)

-- A two-member correlated group: ONE generator produces both values, so
-- whatever relation it establishes between them is true BY CONSTRUCTION
-- of every draw, not true on average or true after a retry -- and ONE
-- shrinker produces both replacements, so the same is true of every
-- candidate.
pair :: (FromCapture a, FromCapture b)
     => Text -> Text -> Text
     -> Gen (a, b) -> Order (a, b) -> (Map Text Text -> Bool)
     -> HoleGroup
pair gname n1 n2 g o lawful = HoleGroup gname [n1, n2] draw sh rk lawful
  where
    draw = rend <$> g
    rend (a, b) = Map.fromList [(n1, renderCap a), (n2, renderCap b)]
    both env = (,) <$> bound1 n1 env <*> bound1 n2 env
    sh env = [ Map.fromList [(n1, r1), (n2, r2)]
             | Right ab <- [both env], (x, y) <- shrinkWith o ab
             , r1 <- renderLawful x, r2 <- renderLawful y ]
    rk env = either (const 0) (rankOf o) (both env)

-- A correlated pair whose members ALSO mean something on their own.
--
-- `pair` above is the right shape when the two holes only ever appear
-- together: with a partner missing, `both` fails, so the group offers no
-- candidates and ranks 0 -- it simply does not shrink. That costs
-- nothing for <someStyle>/<someOtherStyle> (dresses have no candidates
-- to offer in the first place) and nothing for
-- <someSubset>/<someSuperset> (which the corpus only ever writes
-- together).
--
-- It costs a great deal for <someYear>. The step phase had to move
-- `someYear` into a correlated pair with `someOtherYear`, because the
-- span laws (transition's four, and subjects' span-vs-instant) are
-- degenerate or falsely red when the two years collide -- and a
-- collision is not hypothetical at 1 draw in 4104. But <someYear> is
-- also the corpus's most-used hole, appearing ALONE in eight scenarios
-- across scene, census, subjects and resources, and its shrinker (the
-- one that walks a failing year down to the -1405 landmark, and whose
-- well-foundedness cost this project a real cycle to get right) is the
-- diagnosis those scenarios lean on. Registering the pair with `pair`
-- would have silently deleted it from all eight.
--
-- So: when both members are in evidence, this behaves exactly like
-- `pair` -- one correlated draw, one correlated candidate, the pair's
-- own order. When only ONE is (because the scenario mentions only one),
-- it behaves exactly like `solo` on that member, using the member's own
-- order. Nothing is re-bound that the scenario did not mention, and a
-- candidate is still confined, still strictly smaller, and still owes
-- `groupLaw` -- see `shrinkToMinimalWith`'s gates, which now admit a
-- half-present group precisely because a relation with an absent
-- partner is not a relation that can be broken (`distinctPairLaw`
-- states that side of it).
--
-- `pair` is NOT re-expressed in terms of this: its partial-env
-- behaviour (rank 0, no candidates) is a deliberate statement about
-- holes that mean nothing alone, and collapsing the two would turn that
-- statement into an accident of which order was passed.
pairOrSolo :: forall a. (FromCapture a, Eq a)
           => Text -> Text -> Text
           -> Gen (a, a) -> Order (a, a) -> Order a -> (Map Text Text -> Bool)
           -> HoleGroup
pairOrSolo gname n1 n2 g o o1 lawful = HoleGroup gname [n1, n2] draw sh rk lawful
  where
    draw = rend <$> g
    rend (a, b) = Map.fromList [(n1, renderCap a), (n2, renderCap b)]
    sh env = case slice env of
      Just (Left (a, b)) -> [ Map.fromList [(n1, r1), (n2, r2)]
                            | (x, y) <- shrinkWith o (a, b)
                            , r1 <- renderLawful x, r2 <- renderLawful y ]
      Just (Right (n, a)) -> [ Map.singleton n r
                             | a' <- shrinkWith o1 a, r <- renderLawful a' ]
      Nothing -> []
    rk env = case slice env of
      Just (Left ab)      -> rankOf o ab
      Just (Right (_, a)) -> rankOf o1 a
      Nothing             -> 0
    -- Which members this environment carries, read back through the very
    -- captures the corpus parses them with. `Left` is the correlated
    -- case (both present), `Right` the solo one (exactly one present,
    -- named so the candidate re-binds the right hole); `Nothing` is
    -- either nothing present at all or a present binding that does not
    -- read back -- both bottoms of the order, which is the honest answer
    -- for a value we cannot examine.
    slice :: Map Text Text -> Maybe (Either (a, a) (Text, a))
    slice env = case (Map.lookup n1 env, Map.lookup n2 env) of
      (Just _, Just _) -> either (const Nothing) (Just . Left)
                            ((,) <$> bound1 @a n1 env <*> bound1 @a n2 env)
      (Just _, Nothing) -> fmap (Right . (,) n1) (eitherToMaybe (bound1 @a n1 env))
      (Nothing, Just _) -> fmap (Right . (,) n2) (eitherToMaybe (bound1 @a n2 env))
      (Nothing, Nothing) -> Nothing
    eitherToMaybe = either (const Nothing) Just

-- One hole's current binding, parsed back through the very capture the
-- corpus parses it with. Parsing back is what keeps a shrinker honest in
-- both directions: a value it cannot read is not a value it may shrink,
-- and a rendering that does not parse is not a candidate.
bound1 :: FromCapture a => Text -> Map Text Text -> Either Text a
bound1 n env =
  maybe (Left ("no binding for " <> n)) Right (Map.lookup n env) >>= parseCap

-- The other half of that discipline, and the ONE gate a shrink candidate
-- passes to become a binding: a candidate is offered as text only if its
-- rendering survives the round trip its own capture will put it through
-- at substitution time. A value the corpus cannot read back is not a
-- smaller counterexample, it is a broken one -- and the step that would
-- have consumed it reports an obscure capture error naming the capture
-- rather than the shrinker.
--
-- This is also why no `Order` states a type's FRAME. Year's -4004..100,
-- and the fact that year 0 does not exist in this calendar, are declared
-- exactly once -- in `Capture.parseCap` -- and every order, present and
-- future, inherits them here for free instead of restating them and
-- drifting. An order says what SMALLER means; the capture says what
-- LEGAL means; neither has to know the other's business.
renderLawful :: forall a. FromCapture a => a -> [Text]
renderLawful a = [ r | Right (_ :: a) <- [parseCap r] ]
  where r = renderCap a

-- A possibly-empty subset of every piece. R6/the scene's own algebra:
-- the empty scene is the monoid identity, and `sublistOf` genuinely
-- includes `[]` in its codomain, so the identity IS reachable here —
-- see the "genPieces can generate the empty piece set" test, which
-- samples this generator directly to prove it, not just trust the docs.
genPieces :: Gen PieceSet
genPieces = PieceSet . Set.fromList <$> sublistOf [minBound .. maxBound]

-- Final-review Fix 3: year 0 does not exist in this calendar (see
-- Capture.hs's Year instance) -- excluded from the generator's codomain
-- by the same law, not merely by the server happening to reject it after
-- the fact. `suchThat` retries on the one excluded value out of 4105;
-- negligible cost, no risk of divergence.
genYear :: Gen Year
genYear = Year <$> chooseInt (-4004, 100) `suchThat` (/= 0)

-- <someStyle> / <someOtherStyle>: two styles that are DISTINCT BY
-- CONSTRUCTION.
--
-- Not `suchThat (/=)` (rejection sampling, which is distinctness by
-- retry — correct, but it makes "can these ever collide?" a question
-- about the sampler's luck rather than about the generator's codomain),
-- and emphatically not "draw twice and hope". Draw one style, then
-- rotate by a NON-ZERO offset in Z_n: `i` and `i + d` are different
-- residues for every `d` in 1..n-1, so no draw this generator can
-- produce has the two equal. The distinctness test over a run of
-- iterations is then pinning a property the construction already
-- guarantees, which is exactly the right relationship between a law and
-- its test.
--
-- Requires at least two dresses to exist at all (a "different style"
-- is not a thing you can ask for in a one-style world) — pinned as its
-- own test rather than left as an implicit assumption of the modulus.
genStylePair :: Gen (StyleName, StyleName)
genStylePair = do
  i <- chooseInt (0, n - 1)
  d <- chooseInt (1, n - 1)
  pure (styleAt i, styleAt (i + d))
  where
    n = length styleNames
    styleAt k = StyleName (styleNames !! (k `mod` n))

-- <someSubset> / <someSuperset>: a NESTED pair, by construction.
--
-- Draw the superset first, then draw the subset from INSIDE it, so
-- `subset ⊆ superset` holds for every draw this generator can produce —
-- there is no draw in its codomain that violates the nesting, so the
-- subtractive law never spends an iteration red for a reason that has
-- nothing to do with the server.
--
-- Equality (subset == superset) is a LEGAL draw and is deliberately not
-- excluded: `fewer ⊆ more` is a claim about ⊆, and the reflexive case is
-- part of what it claims. But a law tested only on equal sets tests
-- nothing about subtraction, so the DISTRIBUTION matters as much as the
-- codomain: `sublistOf` keeps each of the superset's k pieces
-- independently, so the two coincide with probability 2^-k, and
-- averaging over the superset's own sublistOf draw gives
-- (3/2)^10 / 2^10 ≈ 5.6% — i.e. roughly 94% of draws are PROPER
-- subsets. The distribution test pins a floor of a quarter: far below
-- what the construction actually delivers (so it is not a threshold
-- tuned to today's numbers), far above zero (so a future change that
-- collapsed the pair into equality would fail it loudly).
genNestedPieces :: Gen (PieceSet, PieceSet)
genNestedPieces = do
  PieceSet super <- genPieces
  sub <- sublistOf (Set.toList super)
  pure (PieceSet (Set.fromList sub), PieceSet super)

-- <someYear> / <someOtherYear>: two years that are DISTINCT BY
-- CONSTRUCTION, by exactly the mechanism `genStylePair` uses on dresses
-- -- draw an index, then rotate by a NON-ZERO offset in Z_n, so no draw
-- in this generator's codomain has the two equal.
--
-- The alternative (`genYear` twice, or `suchThat (/=)`) would make
-- transition.feature's four span laws collide one iteration in 4104 --
-- rare enough to look green for a long time and then fail once, for a
-- reason that is not a fact about the server. `transition(a, a)` is a
-- law with its OWN scenario ("no time passing means nothing moves"),
-- written over a single <someYear>; a span law that silently degenerated
-- into it would be that scenario a second time, not the span law.
--
-- The index -> year map is arithmetic, not a list lookup: the calendar
-- has no year 0 (see Capture.Year), so index 0..4003 is -4004..-1 and
-- index 4004..4103 is 1..100 -- 4104 legal years, each reached exactly
-- once, which is what makes the rotation a genuine bijection and the
-- distinctness structural.
yearCount :: Int
yearCount = 4104

yearAt :: Int -> Year
yearAt k = Year (if k < 4004 then k - 4004 else k - 4003)

genYearPair :: Gen (Year, Year)
genYearPair = do
  i <- chooseInt (0, yearCount - 1)
  d <- chooseInt (1, yearCount - 1)
  pure (yearAt i, yearAt ((i + d) `mod` yearCount))

-- <someDetail> / <someOtherDetail>: two tiers, distinct by construction,
-- by the same rotation. detail.feature's invariance law ("detail changes
-- how much is drawn, never what exists") compares the feature sets of two
-- renders; drawing the same tier twice would compare a render with
-- itself, which every server passes.
genDetailPair :: Gen (DetailTier, DetailTier)
genDetailPair = do
  i <- chooseInt (0, n - 1)
  d <- chooseInt (1, n - 1)
  pure (tierAt i, tierAt (i + d))
  where
    n = length ([minBound .. maxBound] :: [DetailTier])
    tierAt k = toEnum (k `mod` n) :: DetailTier

-- ---------- the camera's own holes ----------
--
-- THE GRID. Centers and zooms are drawn on a grid of HUNDREDTHS OF A
-- DEGREE, and the choice is not cosmetic: it is what makes "smaller"
-- a natural number rather than a real, which is what `Order`'s rank
-- contract requires. A hundredth of a degree is also the resolution the
-- corpus's own camera literals are written at (`31.5,35.0`, `zoom 4`,
-- and the frame's own endpoints 0.05 and 89.9), so the grid is the
-- corpus's own precision, not a resolution invented here.
centerGrid :: Int -> Double
centerGrid k = fromIntegral k / 100

-- Division, deliberately, not `fromIntegral k * 0.01`: 0.01 is not
-- representable, so multiplying accumulates its error and 8990 * 0.01
-- need not be the same Double as the literal 89.9 that `parseCap`
-- compares against. `x / 100` is correctly rounded, so it IS that
-- literal, and every drawn endpoint parses back rather than falling one
-- ulp outside the frame.
gridTicks :: Double -> Int
gridTicks d = round (d * 100)

-- <someCenter> / <someOtherCenter>: a distinct pair of points, drawn
-- from a DECLARED box.
--
-- THE BOX IS THE WHOLE GLOBE: latitude -89.90..89.90, longitude
-- -179.99..180.00. Two reasons, and both are about not quantifying over
-- a corner of what the server actually ships:
--
--   * the latitude bounds are the SERVER'S OWN (`build_query` clamps to
--     +/-89.9 before building the cap), so this box is not a choice at
--     all -- it is the set of distinct cameras the API has. Longitude
--     wraps, and the half-open (-180, 180] writes each meridian once.
--   * this canon is GLOBAL, not Levantine. The characterization found
--     833 labels in a 0.09-degree view over Jerusalem, the farthest
--     being Lake Waikaremoana in New Zealand, 148.3 degrees away. A
--     camera law drawn only from the biblical Near East would never
--     put a feature beyond the horizon at all, and "the far side of the
--     globe is never sent" would be a law about an empty set.
--
-- Distinct by construction, by the same Z_n rotation as the style pair:
-- the grid index -> (lat, lon) map is a bijection on [0, n), so two
-- distinct indices are two distinct points, and no draw in the
-- codomain has them equal.
latTickBound :: Int
latTickBound = gridTicks 89.9

lonTickLo, lonTickHi :: Int
lonTickLo = gridTicks (-179.99)
lonTickHi = gridTicks 180

latTickCount, lonTickCount, centerCount :: Int
latTickCount = 2 * latTickBound + 1
lonTickCount = lonTickHi - lonTickLo + 1
centerCount  = latTickCount * lonTickCount

centerAt :: Int -> Center
centerAt k = Center (centerGrid (q - latTickBound)) (centerGrid (r + lonTickLo))
  where (q, r) = k `divMod` lonTickCount

genCenterPair :: Gen (Center, Center)
genCenterPair = do
  i <- chooseInt (0, centerCount - 1)
  d <- chooseInt (1, centerCount - 1)
  pure (centerAt i, centerAt ((i + d) `mod` centerCount))

-- <someZoom>: one draw, but the step vocabulary derives TWO more cameras
-- from it -- camera.feature says "zoom <someZoom> doubled" and
-- "zoom <someZoom> halved" in the two nesting laws.
--
-- Those derived forms go through the server's own clamp
-- (`Capture.zoomDoubled`/`zoomHalved`), which is where the danger is:
-- doubling 90 gives 90, and halving 0.05 gives 0.05. A draw at either
-- endpoint would make "wide" and "narrow" the SAME camera, and both
-- nesting laws would compare a scene with itself -- green for every
-- possible server, which is the exact defect this project already paid
-- for once (7cd31bd's someA/someB). So the generator draws from the
-- sub-window where BOTH derived forms escape the clamp:
-- [2*zoomMin, zoomMax/2] = [0.1, 45]. That window is stated in the
-- clamp's own endpoints, not tuned, and `zoomLaw` below re-states the
-- property itself so a future change to either function is caught rather
-- than assumed.
zoomSafeLoTicks, zoomSafeHiTicks :: Int
zoomSafeLoTicks = gridTicks (zoomMin * 2)
zoomSafeHiTicks = gridTicks (zoomMax / 2)

genZoom :: Gen Zoom
genZoom = Zoom . centerGrid <$> chooseInt (zoomSafeLoTicks, zoomSafeHiTicks)

-- ---------- the shrinkers ----------
--
-- Spec §4: a hole carries a Gen AND a shrink. The shrinker is part of
-- the hole's contract, not a decoration -- §3.2's composition
-- counterexample named fifteen pieces where the true answer was one
-- word, and closing that gap cost a manual narrowing pass.

-- Drop one piece at a time: every subset is reachable by repeated
-- application, and each candidate is strictly smaller -- by CARDINALITY,
-- which is the rank.
pieceSetOrder :: Order PieceSet
pieceSetOrder = Order (\(PieceSet s) -> Set.size s) shr
  where shr (PieceSet s) = [ PieceSet (Set.delete p s) | p <- Set.toList s ]

-- The order a year shrinks along, and the ONE place "a smaller year"
-- is decided.
--
-- -1405 is the frame's landmark -- the year every fixture, every golden
-- view and every conversation in this project is anchored to -- so it is
-- the MINIMUM of the order, rank 0; every other year ranks by magnitude
-- above it. Two consequences, and both are the point:
--
--   * any year may jump straight to -1405, however far away it is,
--     because the landmark is smaller than everything;
--   * -1405 shrinks to NOTHING. It is the bottom, so there is nothing
--     below it to offer.
--
-- The second is not a limitation, it is the fix. The first draft of this
-- shrinker (this task's brief) offered -1405 from every year AND offered
-- ordinary integer-shrinks from -1405 -- so -1405 offered -1400 and
-- -1400 offered -1405 back. Against the live server, where both of those
-- years genuinely fail the identity law, the greedy loop ping-ponged
-- between them until the FUEL ran out, and the reported "minimal"
-- counterexample was wherever the fuel happened to stop. A shrinker that
-- needs the fuel bound to terminate is exactly the mis-written shrinker
-- the fuel bound exists to survive, not a shrinker (MEMORY:
-- types-over-tricks -- the fix belongs in the order, not in a bigger
-- fuel tank).
--
-- This order says nothing about the frame. Year 0 and anything outside
-- -4004..100 are excluded where they are DECLARED -- `Capture.parseCap`
-- -- and `renderLawful` is what applies that declaration to every
-- candidate of every order. So `shrinkWith yearOrder` may well propose
-- Year 0; it never becomes a binding.
yearRank :: Year -> Int
yearRank (Year y) = if y == -1405 then 0 else 1 + abs y

yearOrder :: Order Year
yearOrder = Order yearRank shr
  where
    shr y0@(Year y) =
      [ y' | y' <- map Year ([-1405 | y /= -1405] ++ shrink y)
           , yearRank y' < yearRank y0 ]

-- Toward the earliest constructor; the rank is the constructor's index,
-- so Ground (minBound, rank 0) is the bottom and offers nothing.
pieceOrder :: Order Piece
pieceOrder = Order fromEnum (\p -> takeWhile (< p) [minBound .. maxBound])

-- The nested pair, shrunk WITHOUT ever breaking the nesting.
--
-- Removing a piece from the superset removes it from the subset too (a
-- subset cannot keep what its superset no longer has); removing one from
-- the subset alone is always safe. Both moves strictly reduce
-- |subset| + |superset|, which is the measure that makes the greedy
-- loop terminate over this group.
--
-- Note what is NOT offered: a candidate that shrank one half in
-- isolation. That is the whole reason shrinking attaches to the group --
-- `someSubset` shrunk alone would still be nested (a smaller set of a
-- superset is still inside it), but `someSuperset` shrunk alone would
-- routinely stop containing its partner, and the subtractive law would
-- then be handed a counterexample that no draw could ever have produced.
nestedOrder :: Order (PieceSet, PieceSet)
nestedOrder = Order rk shr
  where
    rk (PieceSet sub, PieceSet super) = Set.size sub + Set.size super
    shr (PieceSet sub, PieceSet super) =
         [ (PieceSet (Set.delete p sub), PieceSet (Set.delete p super))
         | p <- Set.toList super ]
      ++ [ (PieceSet (Set.delete p sub), PieceSet super) | p <- Set.toList sub ]

-- The nesting, as a predicate over the group's RENDERED bindings -- owed
-- by every draw and every shrink candidate alike. An unparseable or
-- missing binding is a violation, not a pass: "I could not check it" and
-- "it holds" must never be the same answer (MEMORY:
-- verify-distinct-not-nonnull).
nestedLaw :: Map Text Text -> Bool
nestedLaw env = case (bound1 "someSubset" env, bound1 "someSuperset" env) of
  (Right (PieceSet sub), Right (PieceSet super)) -> sub `Set.isSubsetOf` super
  _ -> False

-- Distinctness, likewise: the relationship dress-locality depends on.
distinctStyleLaw :: Map Text Text -> Bool
distinctStyleLaw env = case (bound1 "someStyle" env, bound1 "someOtherStyle" env) of
  (Right a, Right b) -> a /= (b :: StyleName)
  _ -> False

-- The three new distinctness laws, all the same shape as
-- `distinctStyleLaw` and all for the same reason: the law that
-- quantifies over the pair compares two responses, and two EQUAL
-- bindings turn that comparison into "a response equals itself" -- true
-- for every server, so a check satisfiable by its own failure mode
-- (MEMORY: verify-distinct-not-nonnull). An unparseable or missing
-- binding is a violation, never a pass: "I could not check it" and
-- "it holds" must not be the same answer.
--
-- Written as one combinator rather than three near-identical copies:
-- the predicate IS "these two holes parse and differ", and the only
-- thing that varies is which two names and at which type.
-- One further distinction this predicate draws that `distinctStyleLaw`
-- does not need to: a member that is ABSENT from the environment (the
-- scenario mentions <someYear> but not <someOtherYear>) is not a gap in
-- the evidence. There is no pair to be distinct, so there is no relation
-- to break -- "not applicable" is the honest answer, and it is what lets
-- `pairOrSolo` shrink a lone <someYear> at all. A member that is PRESENT
-- but does not read back is still a violation, because "I could not read
-- it" and "it holds" must not be the same answer.
-- Carries its type in a `proxy` argument, the same convention
-- `Capture`'s own `capName`/`universe` use, rather than leaning on an
-- ambiguous type variable resolved by TypeApplications at each call
-- site: the type is part of what the law says (two YEARS differ, two
-- TIERS differ), so it belongs in the signature.
distinctPairLaw :: forall proxy a. (FromCapture a, Eq a)
                => proxy a -> Text -> Text -> Map Text Text -> Bool
distinctPairLaw _ n1 n2 env = case (Map.lookup n1 env, Map.lookup n2 env) of
  (Nothing, Nothing) -> True
  (Just _, Nothing)  -> readable n1
  (Nothing, Just _)  -> readable n2
  (Just _, Just _)   -> case (bound1 @a n1 env, bound1 @a n2 env) of
    (Right a, Right b) -> a /= b
    _                  -> False
  where readable n = either (const False) (const True) (bound1 @a n env)

distinctYearLaw :: Map Text Text -> Bool
distinctYearLaw = distinctPairLaw (Proxy @Year) "someYear" "someOtherYear"

distinctDetailLaw :: Map Text Text -> Bool
distinctDetailLaw = distinctPairLaw (Proxy @DetailTier) "someDetail" "someOtherDetail"

distinctCenterLaw :: Map Text Text -> Bool
distinctCenterLaw = distinctPairLaw (Proxy @Center) "someCenter" "someOtherCenter"

-- <someZoom>'s law is NOT distinctness (it is a solo hole) -- it is that
-- the two cameras the STEP VOCABULARY derives from it ("zoom X doubled",
-- "zoom X halved") are genuinely other cameras. A zoom of 90 doubles to
-- 90 and a zoom of 0.05 halves to 0.05, and either would make
-- camera.feature's two nesting laws compare a scene with itself.
--
-- Declared on the group so that the generic pins (every draw and every
-- shrink candidate satisfies its group's law) enforce it automatically,
-- exactly as they do for the correlated pairs -- a solo group with a
-- real precondition is still a group with a law.
zoomLaw :: Map Text Text -> Bool
zoomLaw env = case bound1 "someZoom" env of
  Right z -> zoomDerivesTwoCameras z
  Left _  -> False

-- Styles do not shrink. A dress is not made of smaller dresses, and the
-- only "smaller" move available -- collapsing one style onto the other --
-- is exactly the collision `genStylePair` exists to rule out. Returning
-- no candidates is the honest answer, and it is pinned as such rather
-- than left to be discovered as an empty list nobody meant; the flat
-- rank says the same thing in the order's own terms (every dress pair is
-- the same size, so none is smaller than another).
stylePairOrder :: Order (StyleName, StyleName)
stylePairOrder = Order (const 0) (const [])

-- The year pair shrinks the way a year shrinks -- toward -1405, the
-- frame's landmark -- but ONE MEMBER AT A TIME, and never onto its
-- partner. Both halves matter:
--
--   * shrinking both at once would routinely collapse the pair onto
--     -1405 twice, which is not a distinct pair and therefore not a
--     draw this generator could have produced (the same discipline
--     `nestedOrder` keeps for the nesting).
--   * the rank is the SUM of the two years' own ranks, so every
--     candidate (which strictly lowers one rank and leaves the other
--     alone) strictly lowers the sum -- the well-foundedness `yearOrder`
--     already established, inherited rather than re-derived.
yearPairOrder :: Order (Year, Year)
yearPairOrder = Order rk shr
  where
    rk (a, b) = yearRank a + yearRank b
    shr (a, b) =
         [ (a', b) | a' <- shrinkWith yearOrder a, a' /= b ]
      ++ [ (a, b') | b' <- shrinkWith yearOrder b, b' /= a ]

-- Detail tiers do not shrink, for the reason dresses do not: a tier is
-- not made of smaller tiers. There are exactly three, so a drawn
-- distinct pair is one of six, and the only "smaller" move available --
-- collapsing one tier onto the other -- is precisely the collision
-- `genDetailPair` exists to rule out. The payload ORDER (coarse ships
-- less than fine ships less than ultra) is a fact about the server's
-- output, not about the size of the tier VALUE, so it would not make a
-- counterexample easier to read. Flat rank, no candidates, stated here
-- rather than discovered later as an empty list nobody meant.
detailPairOrder :: Order (DetailTier, DetailTier)
detailPairOrder = Order (const 0) (const [])

-- The camera's landmark, and the bottom of both camera orders: the very
-- point camera.feature's own pinned example looks at
-- ("looking at 31.5,35.0 zoom 4", which detail.feature repeats). Same
-- role -1405 plays for years -- rank 0, shrinks to nothing, and reachable
-- in one jump from anywhere -- so a camera counterexample narrows toward
-- the one camera every reader of this corpus already has in their head.
canonicalCenter :: Center
canonicalCenter = Center 31.5 35.0

canonicalZoom :: Zoom
canonicalZoom = Zoom 4

centerRank :: Center -> Int
centerRank c
  | c == canonicalCenter = 0
  | otherwise = 1 + abs (la - la0) + abs (lo - lo0)
  where
    (la, lo)   = (gridTicks (centerLat c), gridTicks (centerLon c))
    (la0, lo0) = (gridTicks (centerLat canonicalCenter), gridTicks (centerLon canonicalCenter))

-- One center's candidates: the landmark, plus ordinary integer shrinks
-- of each coordinate's tick, filtered to those that genuinely rank
-- lower. The filter is what makes this well-founded even though `shrink`
-- moves toward ZERO while the rank measures distance from the LANDMARK:
-- a move toward zero that overshoots the landmark ranks higher and is
-- simply not offered. (`yearOrder` needs, and has, the identical filter,
-- for the identical reason -- the -1405 <-> -1400 cycle it exists to
-- rule out.)
centerShrinks :: Center -> [Center]
centerShrinks c =
  [ c' | c' <- [ canonicalCenter | c /= canonicalCenter ] ++ moves, centerRank c' < centerRank c ]
  where
    (la, lo) = (centerLat c, centerLon c)
    moves = [ Center (centerGrid la') lo | la' <- shrink (gridTicks la) ]
         ++ [ Center la (centerGrid lo') | lo' <- shrink (gridTicks lo) ]

centerPairOrder :: Order (Center, Center)
centerPairOrder = Order rk shr
  where
    rk (a, b) = centerRank a + centerRank b
    shr (a, b) =
         [ (a', b) | a' <- centerShrinks a, a' /= b ]
      ++ [ (a, b') | b' <- centerShrinks b, b' /= a ]

zoomRank :: Zoom -> Int
zoomRank z@(Zoom v)
  | z == canonicalZoom = 0
  | otherwise = 1 + abs (gridTicks v - gridTicks cz)
  where Zoom cz = canonicalZoom

-- A zoom's candidates: the landmark zoom, plus tick shrinks -- and every
-- candidate must still be a zoom whose doubled and halved forms are
-- distinct cameras (`zoomLaw`'s property, asked of the value rather
-- than restated as a window), because a candidate the DRAW could never
-- have produced is not a smaller counterexample.
zoomOrder :: Order Zoom
zoomOrder = Order zoomRank shr
  where
    shr z@(Zoom v) =
      [ z' | z' <- [ canonicalZoom | z /= canonicalZoom ]
                   ++ [ Zoom (centerGrid t) | t <- shrink (gridTicks v) ]
           , zoomRank z' < zoomRank z
           , zoomDerivesTwoCameras z' ]

-- The property `genZoom`'s window delivers and `zoomOrder` must
-- preserve, stated ONCE as a predicate over the value: both derived
-- cameras really are other cameras. Read off `Capture.zoomDoubled`/
-- `zoomHalved` (which carry the server's clamp) rather than restating
-- the window's endpoints, so a change to the clamp moves this with it.
zoomDerivesTwoCameras :: Zoom -> Bool
zoomDerivesTwoCameras z = zoomDoubled z /= z && zoomHalved z /= z

-- The one and only place a hole name is given meaning. EXPLICIT and
-- TYPED, no name-sniffing/inference: a hole not listed here has no
-- generator, and `runScenarioProperty`/`substituteExamples` must treat
-- that as a loud failure, never a silent pass (requirement 1).
--
-- someA and someB stay SEPARATE solo groups: the composition law needs
-- them independent (that is what fix 7cd31bd restored), and independence
-- is now the structural consequence of being in different groups rather
-- than a property of the seeding formula alone.
--
-- `somePiece` (singular) is registered for Task 12's strengthened
-- omission law; it is here now, with its shrinker, so that task inherits
-- a hole that already narrows instead of one that has to be taught to.
holeGroups :: [HoleGroup]
holeGroups =
  [ solo "somePieces" genPieces pieceSetOrder
  , solo "somePiece"  (elements [minBound .. maxBound] :: Gen Piece) pieceOrder
  , solo "someA"      genPieces pieceSetOrder
  , solo "someB"      genPieces pieceSetOrder
  , pair "stylePair"    "someStyle"  "someOtherStyle"
      genStylePair    stylePairOrder distinctStyleLaw
  , pair "nestedPieces" "someSubset" "someSuperset"
      genNestedPieces nestedOrder    nestedLaw
    -- The step phase's four: the camera's centers and zoom, the detail
    -- axis's tiers, and the span laws' second year. Each carries the
    -- relationship its laws depend on (see the four predicates above),
    -- so no scenario quantified over them can degenerate into comparing
    -- a response with itself.
    -- The one pair whose members also mean something alone: <someYear>
    -- is written on its own in eight scenarios across four files, and
    -- its shrinker is what walks a failing year down to -1405 there.
    -- See `pairOrSolo`.
  , pairOrSolo "yearPair" "someYear" "someOtherYear"
      genYearPair     yearPairOrder  yearOrder distinctYearLaw
  , pair "detailPair"   "someDetail" "someOtherDetail"
      genDetailPair   detailPairOrder distinctDetailLaw
  , pair "centerPair"   "someCenter" "someOtherCenter"
      genCenterPair   centerPairOrder distinctCenterLaw
  , soloLawful "someZoom" genZoom zoomOrder zoomLaw
  ]

-- Every hole name, mapped to the group that draws it. A partition of the
-- hole names, not merely a map into groups: `check` asks this for
-- membership (an unregistered hole is an orphan), and the runner asks it
-- which groups a scenario's holes belong to.
holeRegistry :: Map Text HoleGroup
holeRegistry = Map.fromList [ (h, g) | g <- holeGroups, h <- groupMembers g ]

-- Every "<hole>" token appearing in one raw step body, left to right.
-- Exported (not just used internally by `holesOf`) so `Check.classify`
-- can scan a bare `Step`'s body for holes too, without going through a
-- whole `Scenario` -- that's what lets an UNREGISTERED hole be caught at
-- `check` time regardless of which capture it happens to land in.
holesIn :: Text -> [Text]
holesIn b = case T.breakOn "<" b of
  (_, rest) | T.null rest -> []
  (_, rest) ->
    let (h, rest') = T.breakOn ">" (T.drop 1 rest)
    in h : if T.null rest' then [] else holesIn (T.drop 1 rest')

-- Every "<hole>" token appearing in any step body of a scenario, in
-- first-seen order (duplicates removed by `dedupe` at the call site).
holesOf :: Scenario -> [Text]
holesOf sc = concatMap (holesIn . stepBody) (scSteps sc)

-- First-seen order, genuinely -- a naive `foldr (\x acc -> if x \`elem\`
-- acc then acc else x : acc) []` looks right but actually REVERSES
-- relative order among the first occurrences (try it on [a,b,a,c]: it
-- yields [b,a,c], not [a,b,c]), because foldr conses the LATEST
-- not-yet-seen element it encounters (scanning right-to-left) onto the
-- front. Harmless everywhere this is currently used -- binding lookup is
-- by Map key, and the failing-binding report sorts by key too -- but the
-- name promises an order this shape doesn't deliver, so it earns an
-- explicit accumulator instead.
dedupe :: [Text] -> [Text]
dedupe = go []
  where
    go _ [] = []
    go seen (x : xs)
      | x `elem` seen = go seen xs
      | otherwise     = x : go (x : seen) xs

-- Every "<hole>" token in every step of a scenario gets textually
-- replaced by its bound rendering. `env` need not cover every hole in
-- `sc` for this to typecheck (it's just Text -> Text substitution) --
-- callers (runScenarioProperty, below) are the ones responsible for
-- ensuring every hole actually used has a binding first.
substitute :: Map Text Text -> Scenario -> Scenario
substitute env sc = sc { scSteps = map sub (scSteps sc) }
  where
    sub st = st { stepBody = Map.foldrWithKey
                    (\h v b -> T.replace ("<" <> h <> ">") v b)
                    (stepBody st) env }

-- Final-review Fix 1 (Critical): the seed a hole draws from is a function
-- of BOTH the hole's own name and the iteration index, never the index
-- alone. The pre-fix version (`mkQCGen (fromIntegral i * 7919)`, keyed
-- ONLY on `i`) meant every hole bound at the same iteration -- regardless
-- of name -- drew from the identical point in the identical generator's
-- stream. That is invisible for two DIFFERENT generators (Year vs.
-- PieceSet can't collide), but scene.feature's composition property
-- registers `someA` and `someB` against the SAME generator (`genPieces`,
-- see holeRegistry below): `unGen` is pure, so same generator + same
-- QCGen + same size is the same value, every iteration, for the whole
-- run. someA and someB were therefore never actually independent --
-- always literally the same PieceSet -- which makes the composition
-- law's assertion (`sceneA \`union\` sceneB == union of the parts`)
-- degenerate to `x == x \`union\` x`, true for ANY server behaviour. A
-- "target already met" verdict built on that is an artifact of the
-- generator wiring, not a fact about the server (see MEMORY:
-- verify-distinct-not-nonnull -- a check satisfiable by the failure mode
-- is no check).
--
-- Still fully deterministic (requirement 2: the same scenario run twice
-- must generate the exact same bindings and verdict, including a failing
-- run's counterexample text) -- `holeSeed` is a pure function of
-- (name, i), so nothing here depends on wall-clock time or any other
-- live entropy; the "same scenario run twice" test still holds.
--
-- FNV-1a over the hole name's UTF-8 bytes, folded with the per-iteration
-- multiplier the old code already used: a real, cheap, well-distributed
-- combination of both inputs, not a tuned magic constant chosen to make
-- any particular scenario pass -- the SAME formula runs for every hole,
-- known-colliding or not.
holeSeed :: Text -> Int -> Int
holeSeed name i = fromIntegral (fnv1a (TE.encodeUtf8 name)) * 7919 + i
  where
    fnv1a :: BS.ByteString -> Word64
    fnv1a = BS.foldl' step offsetBasis
    offsetBasis = 14695981039346656037 :: Word64
    prime = 1099511628211 :: Word64
    step h b = (h `xor` fromIntegral b) * prime

-- Draw one GROUP at a given iteration index, keyed by the group's own
-- name too (see `holeSeed` above) -- so two groups sharing a generator
-- in the SAME scenario iteration (someA/someB) draw from genuinely
-- independent points in that generator's stream, instead of both landing
-- on the identical value. Members WITHIN a group share this one draw:
-- that is the whole point of a group, and the only way a relationship
-- between two holes can be established at all.
drawGroup :: HoleGroup -> Int -> Map Text Text
drawGroup g i =
  unGen (groupDraw g) (mkQCGen (holeSeed (groupName g) i)) (min 30 (i + 3))

-- The bindings a scenario mentioning exactly `hs` gets at iteration `i`.
--
-- Each group is drawn ONCE per iteration however many of its members the
-- scenario happens to mention (so a scenario using only <someStyle> gets
-- the same value it would have got alongside <someOtherStyle>), and the
-- result is restricted back to the holes actually present, so a failing
-- iteration's counterexample reports the bindings the scenario really
-- used and nothing else.
--
-- Exported because the correlation LAWS are tested against this, the
-- real thing the runner calls, rather than against a reconstruction of
-- it in the test file.
bindingsFor :: [Text] -> Int -> Map Text Text
bindingsFor = bindingsForWith holeRegistry

-- The draw over an INJECTED registry -- the same split as
-- `shrinkToMinimal`/`shrinkToMinimalWith` above and for the same reason:
-- `holeDefectsWith` (below) needs to draw a scenario's bindings against a
-- registry a TEST builds, not just against the real `holeRegistry`, so
-- its own "does this hole vary / are these two holes independent" check
-- runs the REAL drawing path (`drawGroup`/`groupsIn`) rather than a
-- reconstruction of it.
bindingsForWith :: Map Text HoleGroup -> [Text] -> Int -> Map Text Text
bindingsForWith reg hs i =
  Map.restrictKeys drawn (Set.fromList hs)
  where
    drawn = Map.unions [ drawGroup g i | g <- groupsIn reg hs ]

-- The groups these hole names belong to, each ONCE, in a fixed order
-- (by group name). Both the drawer and the shrinker ask this, so a
-- scenario's groups are enumerated by one rule rather than two -- and
-- the order being fixed is part of shrinking's determinism, since the
-- greedy loop takes the FIRST candidate that still fails.
--
-- Takes the registry rather than closing over `holeRegistry`, so the
-- shrink loop can be run against a registry a TEST builds -- which is
-- the only way to exercise what the loop does with a group that
-- misbehaves, since every group actually registered here behaves.
groupsIn :: Map Text HoleGroup -> [Text] -> [HoleGroup]
groupsIn reg hs = Map.elems
  (Map.fromList [ (groupName g, g) | h <- hs, Just g <- [Map.lookup h reg] ])

-- Diagnosis §7.0's cheapest lesson, made machine-checkable: "a green from
-- a property scenario is worth nothing until you have seen its inputs
-- vary." Two laws over the SAME run of draws (fix 7cd31bd's exact
-- defect, generalized so a future correlated group can't reintroduce it
-- another way):
--
--   Constant h        -- <h> took fewer than two distinct rendered
--                         values across the whole run. A hole pinned to
--                         one value is a constant wearing a generator's
--                         clothes; a law that quantifies over it has no
--                         discriminating power on that axis at all.
--
--   AlwaysEqual h1 h2 -- two DISTINCT holes rendered to the identical
--                         value on EVERY iteration, not merely some. That
--                         "every" is load-bearing: `someSubset` and
--                         `someSuperset` legitimately draw equal values
--                         SOMETIMES (subset is reflexive, and the
--                         generator's own distribution test pins that
--                         proper subsets are merely common, not
--                         universal) -- collapsing that into "any two
--                         iterations equal" would misfire on the corpus's
--                         own real correlated pair. Equal on every
--                         iteration is what fix 7cd31bd actually found:
--                         someA and someB drawing the identical PieceSet
--                         every single time, degenerating the composition
--                         law to `x == x \`union\` x`.
data HoleDefect = Constant Text | AlwaysEqual Text Text deriving (Eq, Show)

-- Draws each of a scenario's REGISTERED holes `n` times through the REAL
-- drawing path (`bindingsForWith`/`drawGroup`, the same functions
-- `runScenarioProperty` itself calls), then checks both laws above.
--
-- Takes the registry as a parameter for the same reason
-- `shrinkToMinimalWith` does: every group actually registered in the
-- real corpus is well-formed (its whole point), so nothing in the real
-- registry can ever reach the Constant/AlwaysEqual code paths --
-- exercising them at all requires a test to build a deliberately
-- defective registry and drive this function with it directly.
--
-- An UNREGISTERED hole (the coverage corpus's forced-orphan holes) is
-- filtered out here, not reported: `classify`'s per-step scan already
-- forces those to VOrphan unconditionally, and reporting them again here
-- as a "constant" or "always-equal" hole (with no generator, they trivially
-- are: an unbound name renders to nothing, always the same nothing) would
-- be the SAME defect reported twice under two different labels.
holeDefectsWith :: Map Text HoleGroup -> Int -> Scenario -> [HoleDefect]
holeDefectsWith reg n sc =
  [ Constant h | (h, vs) <- draws, length (nub vs) < 2 ]
  ++ [ AlwaysEqual h1 h2
     | ((h1, vs1) : rest) <- tails draws, (h2, vs2) <- rest
       -- Equal on EVERY iteration (list equality over the whole run),
       -- not "equal on some" -- see the AlwaysEqual comment above.
     , vs1 == vs2 ]
  where
    hs = [ h | h <- dedupe (holesOf sc), Map.member h reg ]
    envs = [ bindingsForWith reg hs i | i <- [0 .. n - 1] ]
    draws = [ (h, [ Map.findWithDefault "" h e | e <- envs ]) | h <- hs ]

holeDefects :: Int -> Scenario -> [HoleDefect]
holeDefects = holeDefectsWith holeRegistry

-- Run one @property-tagged scenario N times over generated bindings. A
-- scenario with no holes at all is a harmless (if wasteful) degenerate
-- case: every iteration substitutes nothing and re-runs the same body.
--
-- Iterations are counted, not just consumed: a `Skipped` iteration (a
-- draw whose binding cannot exercise this law's precondition -- see
-- World.StepOutcome) is neither a pass nor a failure, and `Run.lawTally`
-- turns an all-skipped run into a Failed naming the count, because a law
-- that never ran must not report green.
runScenarioProperty :: [StepDef] -> World -> Int -> Scenario -> IO LawRun
runScenarioProperty defs w n sc =
  case unregistered of
    (h : _) -> pure $ LawRun
      (Failed ("unregistered property hole <" <> h <> "> in scenario \""
               <> scName sc <> "\" -- add it to Prop.holeRegistry")) 0
    [] -> loop 0 0 ""
  where
    hs = dedupe (holesOf sc)
    unregistered = [ h | h <- hs, h `Map.notMember` holeRegistry ]
    loop i skips lastWhy
      | i >= n = pure (lawTally n skips lastWhy Passed)
      | otherwise = do
          let env = bindingsFor hs i
          v <- runScenario defs w (substitute env sc)
          case v of
            Passed -> loop (i + 1) skips lastWhy
            -- The skipped iteration still names the binding that could
            -- not exercise the law: "12 skipped" without a single
            -- example of WHY is a number nobody can act on.
            Skipped why -> loop (i + 1) (skips + 1) (why <> withBindings env)
            -- Spec §4's forAllShrink: the FIRST failing draw is a
            -- starting point, not the report. Narrow it to a local
            -- minimum before saying anything, so the diagnosis names the
            -- smallest binding that still breaks the law rather than the
            -- first one that happened to.
            Failed _ -> do
              (minEnv, minMsg) <- shrinkToMinimal defs w sc env
              pure . flip LawRun skips . Failed $
                minMsg <> withBindings minEnv
                  -- The original counterexample stays visible: shrinking
                  -- must SHARPEN the report, never hide what was
                  -- actually generated. Omitted when nothing shrank,
                  -- because the tail states a fact about the run.
                  <> (if minEnv == env then ""
                        else "\n    (shrunk from " <> renderBindings env <> ")")
    withBindings env = "\n    with " <> renderBindings env

-- One binding environment as the report writes it. Shared by the "with"
-- line and the "(shrunk from ...)" tail so the two are always in the
-- same shape and the same (key) order -- a reader comparing them is
-- comparing values, not formatting.
--
-- Holes are separated by "; ", not ", ", because a piece set's OWN
-- rendering is comma-separated: "somePieces = journeys, veil, someStyle
-- = slate" makes a reader count commas to find where one binding ends,
-- and gets worse exactly as the counterexample gets more interesting.
-- "somePieces = journeys, veil; someStyle = slate" is parseable by eye.
renderBindings :: Map Text Text -> Text
renderBindings env =
  T.intercalate "; " [ h <> " = " <> val | (h, val) <- Map.toList env ]

-- forAllShrink's semantics over IO: from a known-failing binding
-- environment, repeatedly try replacing ONE GROUP with ONE strictly
-- smaller binding for all of its members at once; keep the first
-- replacement that still fails; stop at a local minimum.
--
-- Why the semantics and not the combinator: QuickCheck's `forAllShrink`
-- wants a pure `Testable`, our scenario body is IO, and -- decisively --
-- this runner's reproducibility rests on `holeSeed`, a pure function of
-- (group name, iteration) that `quickCheckWith`'s replay machinery would
-- take over. Same guarantee, same determinism, no second seeding regime.
--
-- Deterministic (the candidate order is `groupsIn`'s, then the
-- shrinker's own, and no candidate consumes fresh randomness);
-- terminating (every ACCEPTED candidate has a strictly smaller
-- `groupRank` than the bindings it replaces, and the ranks the registry
-- actually declares are genuine naturals, so the environment's total
-- rank strictly decreases at every step and cannot decrease forever).
--
-- The fuel bound is a hard stop, not a tuning knob -- it exists so a
-- mis-written shrinker cannot loop forever. It is not what ends a
-- well-formed run, but be precise about why: that is an argument about
-- the orders registered HERE, each of whose ranks is bounded below by
-- zero, not a structural guarantee of this loop. A `groupRank` that
-- could return ever-smaller negatives would descend forever while
-- satisfying the filter at every step, and the fuel is the only thing
-- that would stop it. That is the case the fuel is for.
--
-- A candidate that SKIPS or PASSES is not a smaller counterexample and
-- is discarded: shrinking may only ever move between failures.
--
-- One property of the descent worth knowing when reading a
-- counterexample: candidates are tried in the shrinker's own order and
-- the FIRST failure wins, so for a piece set (whose candidates drop
-- pieces in ascending constructor order) each step removes the
-- lowest-index piece it can. When several pieces would each fail alone,
-- the survivor reported is therefore the HIGHEST-index one. A single
-- piece in a minimal counterexample is evidence that it fails alone --
-- not, on its own, evidence that it is the only piece that would.
shrinkToMinimal
  :: [StepDef] -> World -> Scenario -> Map Text Text -> IO (Map Text Text, Text)
shrinkToMinimal = shrinkToMinimalWith holeRegistry

-- The loop over an INJECTED registry. Everything real calls
-- `shrinkToMinimal`, which supplies `holeRegistry`; the parameter exists
-- because the guards below are unfalsifiable against a registry whose
-- groups all behave -- every order registered here is well-founded and
-- binds exactly what it declares, so nothing in the real corpus can
-- reach the code that rejects a candidate. A test builds a deliberately
-- misbehaving group and drives the real loop with it.
shrinkToMinimalWith
  :: Map Text HoleGroup
  -> [StepDef] -> World -> Scenario -> Map Text Text -> IO (Map Text Text, Text)
shrinkToMinimalWith reg defs w sc env0 = do
  -- The starting message is re-derived rather than handed in, so that
  -- EVERY message this function can report -- the original included --
  -- comes from the same code path. The fallback is not "no text
  -- available": a draw that failed once and passes on an identical
  -- re-run is a finding in its own right (determinism is a law here),
  -- and the report says so instead of showing an empty reason.
  e0 <- failureOf env0
  go (1000 :: Int) env0
     (maybe "the failing draw did not reproduce on re-run -- this law is \
            \not deterministic" id e0)
  where
    failureOf env = do
      v <- runScenario defs w (substitute env sc)
      pure $ case v of Failed e -> Just e; _ -> Nothing
    -- The three things a candidate must be, CHECKED here rather than
    -- assumed of the shrinker that offered it. Spec.hs pins all three as
    -- laws, which is what makes a shrinker that breaks one LOUD; these
    -- are what make it harmless in the meantime. The draw side of this
    -- module already pins all three of its own accord -- a candidate is
    -- the other way a binding environment comes into existence, and it
    -- owes exactly what a draw owes.
    --
    --   PRESENT. The group must have at least one member in this
    --   environment. `groupsIn` already guarantees that (it enumerates
    --   the groups these hole names belong to), so the gate is written
    --   here as documentation of what a candidate rests on rather than
    --   as a second filter.
    --
    --   This gate used to read COMPLETE -- all of a group's members
    --   bound -- on the reasoning that half a correlated pair cannot be
    --   re-bound lawfully, its partner's value not being in evidence.
    --   That is true when the partner is missing from a SLICE, and it is
    --   still enforced, but by the CONFINED and LAWFUL gates below, not
    --   by this one. It is NOT true when the partner is absent because
    --   the SCENARIO never mentioned it: <someYear> alone is a whole
    --   binding, not half of one, and `pairOrSolo` re-binds it through
    --   its own solo order. Keeping COMPLETE here would have deleted
    --   year shrinking from every scenario that writes <someYear>
    --   without <someOtherYear> -- eight of them -- the moment the two
    --   became one group.
    --
    --   CONFINED to the members the group DECLARES. An undeclared key in
    --   a slice would slip a hole into the environment that the scenario
    --   never mentioned -- and `groupRank` would not notice, because it
    --   reads only declared members, so the rank filter alone does not
    --   catch this. `restrictKeys` is what makes the field comment's
    --   promise ("a candidate replaces EVERY member at once", and only
    --   those) true rather than hoped for.
    --
    --   SMALLER, by the group's own declared rank -- see the header
    --   comment. A strictly smaller rank also implies the bindings
    --   really changed, since rank is a function of them, so no separate
    --   "is it different?" test is needed.
    --
    -- and finally LAWFUL: the relationship the group establishes must
    -- survive the substitution. A restricted slice can still be a
    -- partial one (a shrinker that returns one member of a pair), and
    -- unioning that over `env` keeps the partner's OLD value -- a
    -- (subset, superset) that no draw could have produced. `groupLaw` on
    -- the resulting environment is what rules that out, and it is the
    -- same predicate the draw side is held to.
    candidates env =
      [ next
      | g <- groupsIn reg (Map.keys env)
      , any (`Map.member` env) (groupMembers g)
      , slice <- groupShrink g env
      , let next = Map.union (Map.restrictKeys slice (Set.fromList (groupMembers g))) env
      , groupRank g next < groupRank g env
      , groupLaw g next
      ]
    go fuel env msg
      | fuel <= 0 = pure (env, msg)
      | otherwise = attempt (candidates env)
      where
        attempt [] = pure (env, msg)
        attempt (c : cs) = do
          r <- failureOf c
          case r of
            Just msg' -> go (fuel - 1) c msg'
            Nothing   -> attempt cs

-- For the totality check ONLY (Check.dehole, applied only when the
-- enclosing scenario is @property-tagged — see Check.hs): every
-- registered hole in a raw step body is replaced with ONE fixed,
-- deterministic example value (seed 1, size 3 — arbitrary but stable),
-- so a capture that validates its input (Piece, Year, Style) sees a real
-- value instead of literal "<hole>" text, and a capture that does NOT
-- validate (UrlPath, which only rejects whitespace) is not fooled into
-- matching on a hole that merely happens to contain no whitespace of its
-- own (ruling R33). An UNREGISTERED hole is deliberately left untouched
-- here — it is not this function's job to fail loudly (it has no
-- scenario to name in an error). `Check.classify` scans for that case
-- itself, BEFORE calling this function, using `holesIn` above; the
-- run-time equivalent (naming the scenario too) is
-- `runScenarioProperty`'s own check, just above.
-- THE gate: whether a scenario with these tags gets its holes substituted
-- before a step body is examined statically.
--
-- Review finding (round 1, Important): this rule used to exist TWICE --
-- `Check.classify` and `Vocab.expectedVocab` each re-expressed "if the
-- scenario is @property-tagged, substitute; otherwise don't" in their own
-- words, with no shared function and nothing pinning the two copies
-- together. Same predicate, same substitution, two independent
-- definitions: the layer-name-twice defect class. The moment the gate
-- becomes feature-tag-aware, or the substitution becomes scenario-aware,
-- the two copies diverge SILENTLY -- and the symptom is not a red test
-- but a deleted or wrong Vocabulary block in the owner's hand-written
-- corpus, discovered by a human reading a file.
--
-- One function, called by both. The gate's REASONING lives in Check.hs's
-- comment (which spells out the mirror-image consequences of getting it
-- wrong in either direction); this is the single place it is DECIDED.
-- The condition is exactly the one `Prop.runWithProperties`'s `run1`
-- uses to decide whether to substitute at run time, which is the fact
-- both static callers are trying to predict.
-- THE property-tag predicate. Ruling R60/R77: this test used to be
-- written out independently in three places -- `deholeFor` below,
-- `runWithProperties`'s `run1` (the runtime's own copy of the exact
-- condition `deholeFor`'s comment says it predicts), and, before the
-- comment sweep, `Vocab.expectedVocab` (retired when `deholeFor` was
-- pulled out as the one shared gate). A previous review caught the
-- first two duplicates and deferred retiring `run1`'s as a documented
-- minor; this retires it. `Check.checkDir`'s DEGENERATE-HOLE wiring is a
-- FOURTH call site with the exact same question ("is this scenario
-- @property-tagged?") and uses this too, so the count of independent
-- copies goes to one, not up.
isProperty :: [Tag] -> Bool
isProperty tags = Tag "property" `elem` tags

deholeFor :: [Tag] -> Text -> Text
deholeFor tags
  | isProperty tags = substituteExamples
  | otherwise        = id

substituteExamples :: Text -> Text
substituteExamples b0 = foldr rep b0 (concatMap example holeGroups)
  where
    -- One draw per GROUP, so a correlated group's example values are
    -- related to each other here exactly the way they will be at run
    -- time -- `check` never sees a subset/superset pair that a real
    -- iteration could not have produced.
    example g = Map.toList (unGen (groupDraw g) (mkQCGen 1) 3)
    rep :: (Text, Text) -> Text -> Text
    rep (h, v) = T.replace ("<" <> h <> ">") v

-- How many iterations a @property law must run, or why the requested
-- count is not a count at all.
--
-- Review finding (round 1): `--property-runs 0` is not a CHEAP run, it
-- is a SILENT one. With no iterations, `runScenarioProperty`'s loop
-- terminates immediately having examined nothing; `lawTally`'s
-- `iterations > 0` guard cannot fire (0 skipped of 0 is not "all
-- skipped" by any honest reading); and every @property law in both
-- corpora reports a green tick for zero evidence. That is the precise
-- failure this whole stage exists to outlaw -- a check satisfiable by
-- its own failure mode (MEMORY: verify-distinct-not-nonnull) -- and the
-- knob that produces it is the one CI budget pressure reaches for
-- first. So it is refused at PARSE time, loudly, rather than accepted
-- into a run whose table looks like a pass.
--
-- Lives here, not in the option parser, so the law is testable: the
-- executable's reader is a two-line adapter over this function (app/
-- Main.hs), and Spec pins both directions against the function itself.
checkPropertyRuns :: Int -> Either String Int
checkPropertyRuns n
  | n >= 1 = Right n
  | otherwise = Left $
      "--property-runs must be at least 1 (got " <> show n <> "). "
        <> "A run of " <> show n <> " iterations does not check a @property law "
        <> "less thoroughly -- it does not check it at all, and every such law "
        <> "would report green having examined nothing."

-- Plain scenarios run once; @property scenarios run `n` times over
-- generated bindings (first failure's Verdict already carries its
-- binding values, from runScenarioProperty above).
runWithProperties :: [StepDef] -> World -> Int -> [FilePath] -> IO [ScenarioResult]
runWithProperties defs w n files = fmap concat . mapM one $ files
  where
    one p = do
      -- Fix 4: shared explicit-UTF-8 reader, not a plain TIO.readFile --
      -- see World.readFeatureFile's comment.
      src <- readFeatureFile p
      case parseFeature p src of
        Left e  -> pure [ScenarioResult (T.pack p) "PARSE" [] (Failed e) 0]
        -- R97: `runnableScenarios` -- so a hole in the Background is the
        -- SAME hole as one in the scenario body. `holesOf` scans
        -- `scSteps`, so one draw per iteration covers both, and
        -- `substitute` and the shrinker reach both. A separately-drawn
        -- preamble could get out of step with the body it sets up.
        Right f -> mapM (run1 (ftTitle f)) (runnableScenarios f)
    run1 ft sc
      | isProperty (scTags sc) =
          mk ft sc <$> runScenarioProperty defs w n sc
      | otherwise =
          mk ft sc . lawOnce <$> runScenario defs w sc
    mk ft sc (LawRun v s) = ScenarioResult ft (scName sc) (scTags sc) v s
